/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jartoexewrapper;

import com.formdev.flatlaf.FlatLightLaf; // Import FlatLaf
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.SwingWorker; // Import SwingWorker
import javax.swing.border.LineBorder;
import java.io.BufferedReader; // Added for process output reading
import java.io.InputStreamReader; // Added for process output reading
import java.util.List; // Added for process method signature

/**
 *
 * @author Herat Afghan Asia
 */
public class jartoexe extends javax.swing.JFrame {

    String jarDirectory, jarName;
    String command;
    private javax.swing.JButton btnCancel; // Added cancel button
    private PackagingWorker currentWorker; // To hold the current worker instance

    /**
     * Creates new form frame1
     */
    public jartoexe() {
        initComponents();

        // Initialize and configure btnCancel
        btnCancel = new javax.swing.JButton();
        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Cancel the current conversion process");
        btnCancel.setEnabled(false);
        btnCancel.addActionListener(evt -> {
            if (currentWorker != null && !currentWorker.isDone()) {
                currentWorker.cancel(true); // true to interrupt the thread
            }
        });

        // Add btnCancel to jPanel6. This will require GUI builder adjustment for proper layout.
        // For now, it might just stack or not be visible depending on jPanel6's layout.
        // A FlowLayout would be simple for jPanel6 if it only contains these two buttons.
        jPanel6.add(btnCancel);
        // To make it potentially visible if jPanel6 uses a more flexible layout or if one is set:
        // Example: jPanel6.setLayout(new java.awt.FlowLayout()); // This would change NetBeans' design
        // jPanel6.add(btnWarp); // Re-add btnWarp if layout is changed
        // jPanel6.add(btnCancel);
        // The GUI builder in Netbeans would be the correct tool to adjust jPanel6's layout
        // to include two buttons side-by-side or one below the other.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtJarFile = new javax.swing.JTextField();
        btnJarFile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txticonPath = new javax.swing.JTextField();
        btnSelectIconPath = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtOutPut = new javax.swing.JTextField();
        btnBrowseOutput = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rbtEXE = new javax.swing.JRadioButton();
        rbtMSI = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtAppVersion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAppName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtVendorName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Progressbar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaOutputResult = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnWarp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(570, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input / Output"));

        jLabel11.setText("Jar File *");

        txtJarFile.setToolTipText("the JAR File that you want to Convert");

        btnJarFile.setText("Select");
        btnJarFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJarFileActionPerformed(evt);
            }
        });

        jLabel2.setText("Icon Path .ico");

        txticonPath.setToolTipText("the icon for your application with .ico extension");

        btnSelectIconPath.setText("Select");
        btnSelectIconPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectIconPathActionPerformed(evt);
            }
        });

        jLabel3.setText("Output exe File *");

        txtOutPut.setToolTipText("the folder or path that you want to save your converted file");

        btnBrowseOutput.setText("Browse");
        btnBrowseOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtOutPut, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowseOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txticonPath, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectIconPath, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtJarFile, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJarFile, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJarFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJarFile))
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txticonPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectIconPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOutPut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseOutput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnJarFile.getAccessibleContext().setAccessibleName("");
        btnSelectIconPath.getAccessibleContext().setAccessibleName("");
        btnBrowseOutput.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 543, 170);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Application "));

        jLabel4.setText("Application Type *");

        buttonGroup1.add(rbtEXE);
        rbtEXE.setSelected(true);
        rbtEXE.setText("EXE");

        buttonGroup1.add(rbtMSI);
        rbtMSI.setText("MSI");

        jLabel6.setText("Application Version (Ex: 1.0.0) *");

        txtAppVersion.setToolTipText("application version example (1.0.0 or 1.2.4)");

        jLabel7.setText("Application Output Name *");

        txtAppName.setToolTipText("the name of your software");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(rbtEXE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(txtAppVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rbtMSI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(rbtEXE)
                    .addComponent(rbtMSI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(txtAppVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(txtAppName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(6, 180, 543, 100);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendor Information"));

        jLabel5.setText("Company (Publisher) Name *");

        txtVendorName.setToolTipText("the owner name company or publisher");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(6, 290, 543, 79);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        txtAreaOutputResult.setEditable(false);
        txtAreaOutputResult.setColumns(20);
        txtAreaOutputResult.setRows(5);
        txtAreaOutputResult.setToolTipText("Converting Result");
        jScrollPane1.setViewportView(txtAreaOutputResult);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Progressbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(6, 410, 543, 140);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("This Application Requiered Wix3 if you don't install it on your system please download and install it");

        jTextField7.setEditable(false);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField7.setText("https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe");
        jTextField7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel9.setText("From:  ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(6, 550, 543, 36);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));

        btnWarp.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.hoverBorderColor"));
        btnWarp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnWarp.setText("Convert");
        btnWarp.setToolTipText("Press to Convert");
        btnWarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnWarp, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnWarp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(6, 370, 540, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reset() {
        txtAreaOutputResult.setText("");
        Progressbar.setValue(0);
    }

    private String validateFields() {
        StringBuilder errors = new StringBuilder();

        // Validate inputJarFile
        if (txtJarFile.getText() == null || txtJarFile.getText().trim().isEmpty()) {
            txtJarFile.setBorder(new LineBorder(Color.PINK, 1));
            errors.append("- JAR File is required.\n");
        } else {
            txtJarFile.setBorder(UIManager.getBorder("TextField.border"));
        }

        // Validate outputFile
        if (txtOutPut.getText() == null || txtOutPut.getText().trim().isEmpty()) {
            txtOutPut.setBorder(new LineBorder(Color.PINK, 1));
            errors.append("- Output EXE File path is required.\n");
        } else {
            txtOutPut.setBorder(UIManager.getBorder("TextField.border"));
        }

        // Validate appName
        if (txtAppName.getText() == null || txtAppName.getText().trim().isEmpty()) {
            txtAppName.setBorder(new LineBorder(Color.PINK, 1));
            errors.append("- Application Output Name is required.\n");
        } else {
            txtAppName.setBorder(UIManager.getBorder("TextField.border"));
        }

        // Validate appVersion
        if (txtAppVersion.getText() == null || txtAppVersion.getText().trim().isEmpty()) {
            txtAppVersion.setBorder(new LineBorder(Color.PINK, 1));
            errors.append("- Application Version is required.\n");
        } else {
            // Optional: Add regex for version format e.g., "X.Y.Z"
            if (!txtAppVersion.getText().matches("\\d+(\\.\\d+){0,2}")) {
                 txtAppVersion.setBorder(new LineBorder(Color.ORANGE, 1)); // Use a different color for warnings or format errors
                 errors.append("- Application Version format is not standard (e.g., 1.0 or 1.0.0).\n");
            } else {
                txtAppVersion.setBorder(UIManager.getBorder("TextField.border"));
            }
        }

        // Validate vendorName
        if (txtVendorName.getText() == null || txtVendorName.getText().trim().isEmpty()) {
            txtVendorName.setBorder(new LineBorder(Color.PINK, 1));
            errors.append("- Company (Publisher) Name is required.\n");
        } else {
            txtVendorName.setBorder(UIManager.getBorder("TextField.border"));
        }

        // Validate icon path if provided
        String iconPath = txticonPath.getText();
        if (iconPath != null && !iconPath.trim().isEmpty()) {
            if (!iconPath.toLowerCase().endsWith(".ico")) {
                txticonPath.setBorder(new LineBorder(Color.ORANGE, 1));
                errors.append("- Icon file should be a .ico file.\n");
            } else {
                File iconFile = new File(iconPath);
                if (!iconFile.exists() || !iconFile.isFile()) {
                    txticonPath.setBorder(new LineBorder(Color.PINK, 1));
                    errors.append("- Icon file not found at the specified path.\n");
                } else {
                    txticonPath.setBorder(UIManager.getBorder("TextField.border"));
                }
            }
        } else {
            // If no icon path, ensure border is reset (if it was previously in error state)
            txticonPath.setBorder(UIManager.getBorder("TextField.border"));
        }


        return errors.toString();
    }

    private void btnWarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarpActionPerformed
        reset();
        String validationErrors = validateFields();

        if (!validationErrors.isEmpty()) {
            // Display specific errors collected from validateFields
            JOptionPane.showMessageDialog(this, "Please correct the following errors:\n\n" + validationErrors, "Validation Error", JOptionPane.ERROR_MESSAGE);
            return; // Stop further execution if validation fails
        }

        // If validation passed, proceed to gather data and execute
        String inputJarFile = jarDirectory;
        String jarFile = jarName;
        String iconPathText = txticonPath.getText(); // Use a different variable name to avoid confusion with the 'command' field
        String outputFile = txtOutPut.getText();
        String appName = txtAppName.getText();
        String appVersion = txtAppVersion.getText();
        String vendorName = txtVendorName.getText();
        String appType = rbtEXE.isSelected() ? "exe" : "msi";

        // Safeguard: Ensure jarDirectory and jarName were set (e.g. by selecting a JAR file)
        // This should ideally be fully covered by validateFields, but an extra check doesn't hurt.
        if (inputJarFile == null || jarFile == null) {
            JOptionPane.showMessageDialog(this, "Critical error: JAR file path or name is not set. Please re-select the JAR file.", "Input Error", JOptionPane.ERROR_MESSAGE);
            txtJarFile.setBorder(new LineBorder(Color.RED, 2)); // Highlight the problematic field
            return;
        }

        // Construct the jpackage command using the JPackageService
        command = JPackageService.buildJPackageCommand(
            appName, inputJarFile, jarFile, appType, iconPathText,
            appVersion, outputFile, vendorName
        );

        btnWarp.setEnabled(false);
        btnCancel.setEnabled(true); // Enable cancel button
        currentWorker = new PackagingWorker(command); // Assign to currentWorker
        currentWorker.addPropertyChangeListener(propertyChangeEvent -> {
            if ("progress".equals(propertyChangeEvent.getPropertyName())) {
                Progressbar.setValue((Integer) propertyChangeEvent.getNewValue());
            }
        });
        currentWorker.execute();

    }//GEN-LAST:event_btnWarpActionPerformed

    private void printMessage(String message) {
        SwingUtilities.invokeLater(() -> txtAreaOutputResult.append(message + "\n"));
    }

    private void btnSelectIconPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectIconPathActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Icon File");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // Set file filter for .ico files
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".ico");
            }

            @Override
            public String getDescription() {
                return "Icon Files (*.ico)";
            }
        });

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txticonPath.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSelectIconPathActionPerformed

    private void btnJarFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJarFileActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select JAR File");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);  // Only JAR files allowed

        // Optionally, filter only JAR files
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".jar");
            }

            @Override
            public String getDescription() {
                return "JAR Files (*.jar)";
            }
        });

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txtJarFile.setText(selectedFile.getAbsolutePath());  // Set the JAR file name in txtJarFile
            jarDirectory = selectedFile.getParent();
            jarName = selectedFile.getName();
        }
    }//GEN-LAST:event_btnJarFileActionPerformed

    private void btnBrowseOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseOutputActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Output Directory");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedDirectory = fileChooser.getSelectedFile();
            txtOutPut.setText(selectedDirectory.getAbsolutePath());
        }
    }//GEN-LAST:event_btnBrowseOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatLaf look and feel */
        try {
            FlatLightLaf.setup();
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf, falling back.");
            // Fallback to Nimbus or other L&Fs
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex2) {
                java.util.logging.Logger.getLogger(jartoexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex2);
            } catch (InstantiationException ex2) {
                java.util.logging.Logger.getLogger(jartoexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex2);
            } catch (IllegalAccessException ex2) {
                java.util.logging.Logger.getLogger(jartoexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex2);
            } catch (javax.swing.UnsupportedLookAndFeelException ex2) {
                java.util.logging.Logger.getLogger(jartoexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex2);
            }
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
            //</editor-fold>
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jartoexe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progressbar;
    private javax.swing.JButton btnBrowseOutput;
    private javax.swing.JButton btnJarFile;
    private javax.swing.JButton btnSelectIconPath;
    private javax.swing.JButton btnWarp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton rbtEXE;
    private javax.swing.JRadioButton rbtMSI;
    private javax.swing.JTextField txtAppName;
    private javax.swing.JTextField txtAppVersion;
    private javax.swing.JTextArea txtAreaOutputResult;
    private javax.swing.JTextField txtJarFile;
    private javax.swing.JTextField txtOutPut;
    private javax.swing.JTextField txtVendorName;
    private javax.swing.JTextField txticonPath;
    // End of variables declaration//GEN-END:variables

    private class PackagingWorker extends SwingWorker<Void, String> {
        private String commandToExecute;

        public PackagingWorker(String command) {
            this.commandToExecute = command;
        }

        @Override
        protected Void doInBackground() throws Exception {
            publish("Starting jpackage process...");
            setProgress(0);

            ProcessBuilder processBuilder;
            String osName = System.getProperty("os.name").toLowerCase();
            if (osName.contains("win")) {
                processBuilder = new ProcessBuilder("cmd", "/c", commandToExecute);
            } else {
                // Assuming Linux, macOS, or other Unix-like systems
                processBuilder = new ProcessBuilder("sh", "-c", commandToExecute);
            }
            processBuilder.redirectErrorStream(true); // Combine output and error streams

            Process process = null; // Initialize process to null
            try {
                process = processBuilder.start();
                publish("Executing jpackage command: " + commandToExecute);

                try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                    String line;
                    int progress = 0;
                    while ((line = reader.readLine()) != null) {
                        if (isCancelled()) {
                            publish("Process cancellation requested...");
                            process.destroy(); // Attempt to destroy the process
                            break;
                        }
                        publish(line);
                        // Basic progress estimation based on typical jpackage output
                        // This is a simple heuristic and might need refinement
                    if (line.contains("step") || line.contains("Step")) { // General step reporting
                        // Try to parse step X/Y
                        String[] parts = line.split("\\s+");
                        for(String part : parts) {
                            if (part.matches("\\d+/\\d+")) {
                                String[] nums = part.split("/");
                                try {
                                    int currentStep = Integer.parseInt(nums[0]);
                                    int totalSteps = Integer.parseInt(nums[1]);
                                    if (totalSteps > 0) {
                                        progress = (int) (((double) currentStep / totalSteps) * 80); // Cap at 80% for packaging phase
                                    }
                                    break;
                                } catch (NumberFormatException e) {
                                    // Ignore if parsing fails
                                }
                            }
                        }
                    } else if (line.toLowerCase().contains("creating application image") || line.toLowerCase().contains("preparing application image")) {
                        progress = Math.max(progress, 10);
                    } else if (line.toLowerCase().contains("creating msi package") || line.toLowerCase().contains("creating exe") || line.toLowerCase().contains("creating installer")) {
                        progress = Math.max(progress, 30);
                    } else if (line.toLowerCase().contains("bundling")) {
                        progress = Math.max(progress, 50);
                    } else if (line.toLowerCase().contains("finished")) {
                         progress = Math.max(progress, 80); // Still leave some room for final steps
                    }
                    setProgress(Math.min(progress, 95)); // Cap at 95% until process fully exits
                }
            } // end of try-with-resources for BufferedReader

            if (isCancelled()) {
                // If process is not null and is alive, destroy it.
                // This ensures that if cancellation happened just before waitFor, we still try to kill it.
                if (process != null && process.isAlive()) {
                    process.destroy();
                }
                publish("Packaging process was actively cancelled.");
                // Throwing CancellationException here ensures done() method handles it via its catch block.
                throw new java.util.concurrent.CancellationException("Process cancelled by user.");
            }

            int exitCode = process.waitFor(); // This might throw InterruptedException if cancel(true) was called earlier.
                                            // SwingWorker handles InterruptedException by transitioning to CANCELLED state.
            setProgress(100);

            if (exitCode == 0) {
                publish("jpackage process completed successfully.");
            } else {
                // If we reach here and it's cancelled, it's a bit ambiguous.
                // However, the explicit check above should catch most UI-triggered cancellations.
                // If cancel(true) interrupted waitFor(), then CancellationException is thrown by get() in done().
                publish("jpackage process failed with exit code: " + exitCode);
                throw new IOException("jpackage process failed with exit code: " + exitCode + ". Check output for details.");
            }
            return null;
        } catch (InterruptedException e) {
            // Handle InterruptedException, which occurs if the thread is interrupted (e.g., by cancel(true))
            if (process != null && process.isAlive()) {
                process.destroy(); // Ensure process is killed if thread is interrupted
            }
            publish("Packaging process interrupted.");
            Thread.currentThread().interrupt(); // Preserve interrupt status
            throw new java.util.concurrent.CancellationException("Process interrupted and cancelled by user.");
        } finally {
            // Optional: any other cleanup specific to doInBackground
        }
    }
        @Override
        protected void process(List<String> chunks) { // Corrected to use java.util.List
            for (String message : chunks) {
                printMessage(message);
            }
        }

        @Override
        protected void done() {
            // This will be called when doInBackground() is finished
            // Re-enable button, show final messages, etc.
            try {
                get(); // Call get to rethrow any exception caught during doInBackground
                Progressbar.setValue(100);
                printMessage("Packaging completed successfully (via SwingWorker).");
                JOptionPane.showMessageDialog(jartoexe.this, "Converted successfully!", "Result", JOptionPane.INFORMATION_MESSAGE);
            } catch (java.util.concurrent.CancellationException e) {
                printMessage("Packaging process was cancelled by the user.");
                JOptionPane.showMessageDialog(jartoexe.this, "Process Cancelled", "Cancelled", JOptionPane.WARNING_MESSAGE);
                Progressbar.setValue(0); // Reset progress bar on cancellation
            } catch (Exception e) {
                e.printStackTrace();
                printMessage("An error occurred: " + e.getMessage());
                JOptionPane.showMessageDialog(jartoexe.this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } finally {
                btnWarp.setEnabled(true);
                btnCancel.setEnabled(false); // Disable cancel button
                currentWorker = null; // Clear current worker
            }
        }
    }
}
