/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jartoexewrapper;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;

/**
 *
 * @author Herat Afghan Asia
 */
public class jartoexe extends javax.swing.JFrame {

    String jarDirectory, jarName;
    String command;

    /**
     * Creates new form frame1
     */
    public jartoexe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtJarFile = new javax.swing.JTextField();
        btnJarFile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txticonPath = new javax.swing.JTextField();
        btnSelectIconPath = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtOutPut = new javax.swing.JTextField();
        btnBrowseOutput = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rbtEXE = new javax.swing.JRadioButton();
        rbtMSI = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtAppVersion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAppName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtVendorName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        Progressbar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaOutputResult = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnWarp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(570, 630));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input / Output"));

        jLabel11.setText("Jar File *");

        txtJarFile.setToolTipText("the JAR File that you want to Convert");

        btnJarFile.setText("Select");
        btnJarFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJarFileActionPerformed(evt);
            }
        });

        jLabel2.setText("Icon Path .ico");

        txticonPath.setToolTipText("the icon for your application with .ico extension");

        btnSelectIconPath.setText("Select");
        btnSelectIconPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectIconPathActionPerformed(evt);
            }
        });

        jLabel3.setText("Output exe File *");

        txtOutPut.setToolTipText("the folder or path that you want to save your converted file");

        btnBrowseOutput.setText("Browse");
        btnBrowseOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtOutPut, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowseOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txticonPath, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSelectIconPath, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtJarFile, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJarFile, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJarFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJarFile))
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txticonPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectIconPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOutPut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseOutput))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnJarFile.getAccessibleContext().setAccessibleName("");
        btnSelectIconPath.getAccessibleContext().setAccessibleName("");
        btnBrowseOutput.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 6, 543, 170);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Application "));

        jLabel4.setText("Application Type *");

        buttonGroup1.add(rbtEXE);
        rbtEXE.setSelected(true);
        rbtEXE.setText("EXE");

        buttonGroup1.add(rbtMSI);
        rbtMSI.setText("MSI");

        jLabel6.setText("Application Version (Ex: 1.0.0) *");

        txtAppVersion.setToolTipText("application version example (1.0.0 or 1.2.4)");

        jLabel7.setText("Application Output Name *");

        txtAppName.setToolTipText("the name of your software");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(rbtEXE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(txtAppVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(rbtMSI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(rbtEXE)
                    .addComponent(rbtMSI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(7, 7, 7)
                        .addComponent(txtAppVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(7, 7, 7)
                        .addComponent(txtAppName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(6, 180, 543, 100);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendor Information"));

        jLabel5.setText("Company (Publisher) Name *");

        txtVendorName.setToolTipText("the owner name company or publisher");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVendorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txtVendorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(6, 290, 543, 79);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));

        txtAreaOutputResult.setEditable(false);
        txtAreaOutputResult.setColumns(20);
        txtAreaOutputResult.setRows(5);
        txtAreaOutputResult.setToolTipText("Converting Result");
        jScrollPane1.setViewportView(txtAreaOutputResult);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Progressbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(Progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(6, 410, 543, 140);

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("This Application Requiered Wix3 if you don't install it on your system please download and install it");

        jTextField7.setEditable(false);
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField7.setText("https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe");
        jTextField7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel9.setText("From:  ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(6, 550, 543, 36);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 1, 1, 1));

        btnWarp.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.hoverBorderColor"));
        btnWarp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnWarp.setText("Convert");
        btnWarp.setToolTipText("Press to Convert");
        btnWarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnWarp, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnWarp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(6, 370, 540, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reset() {
        txtAreaOutputResult.setText("");
        Progressbar.setValue(0);
    }

    private boolean checkFields() {
        boolean allValid = true; // Flag to track if all fields are valid

        // Validate inputJarFile
        if (txtJarFile.getText() == null || txtJarFile.getText().trim().isEmpty()) {
            txtJarFile.setBorder(new LineBorder(Color.PINK, 1));
            allValid = false;
        } else {
            txtJarFile.setBorder(UIManager.getBorder("TextField.border"));
        }

        // Validate outputFile
        if (txtOutPut.getText() == null || txtOutPut.getText().trim().isEmpty()) {
            txtOutPut.setBorder(new LineBorder(Color.PINK, 1));
            allValid = false;
        } else {
            txtOutPut.setBorder(UIManager.getBorder("TextField.border"));
        }

        // Validate appName
        if (txtAppName.getText() == null || txtAppName.getText().trim().isEmpty()) {
            txtAppName.setBorder(new LineBorder(Color.PINK, 1));
            allValid = false;
        } else {
            txtAppName.setBorder(UIManager.getBorder("TextField.border"));
        }

        // Validate appVersion
        if (txtAppVersion.getText() == null || txtAppVersion.getText().trim().isEmpty()) {
            txtAppVersion.setBorder(new LineBorder(Color.PINK, 1));
            allValid = false;
        } else {
            txtAppVersion.setBorder(UIManager.getBorder("TextField.border"));
        }

        // Validate vendorName
        if (txtVendorName.getText() == null || txtVendorName.getText().trim().isEmpty()) {
            txtVendorName.setBorder(new LineBorder(Color.PINK, 1));
            allValid = false;
        } else {
            txtVendorName.setBorder(UIManager.getBorder("TextField.border"));
        }

        return allValid;
    }

    private void btnWarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarpActionPerformed
        reset();
        String inputJarFile = jarDirectory;
        String iconPath = txticonPath.getText();
        String outputFile = txtOutPut.getText();
        String appName = txtAppName.getText();
        String appVersion = txtAppVersion.getText();
        String vendorName = txtVendorName.getText();
        String jarFile = jarName;
        String appType = rbtEXE.isSelected() ? "exe" : "msi";

        // Validate fields
        if (checkFields()) {
            if (txticonPath.getText().equals("")) {
                command = String.format(
                        "jpackage --name %s --input \"%s\" --main-jar %s --type %s --app-version %s --dest \"%s\" --vendor \"%s\" --win-shortcut --win-dir-chooser",
                        appName, inputJarFile, jarFile, appType, appVersion, outputFile, vendorName
                );
            } else {
                command = String.format(
                        "jpackage --name %s --input \"%s\" --main-jar %s --type %s --icon \"%s\" --app-version %s --dest \"%s\" --vendor \"%s\" --win-shortcut --win-dir-chooser",
                        appName, inputJarFile, jarFile, appType, iconPath, appVersion, outputFile, vendorName
                );
            }

            // Execute the packaging process in a separate thread
            Thread packagingThread = new Thread(() -> {
                try {
                    btnWarp.setEnabled(false);
                    // Start the process and print "Starting process..."
                    printMessage("Starting process...");
                    Process process = Runtime.getRuntime().exec(command);

                    
                    Thread.sleep(10000); 
                    printMessage("Working...");
                    Progressbar.setValue(10);


                    Thread.sleep(20000); 
                    printMessage("Almost done...");
                    Progressbar.setValue(40);


                    Thread.sleep(20000); 
                    printMessage("Packaging...");
                    Progressbar.setValue(60);

                    process.waitFor(); // Wait for the process to finish
                    printMessage("Packaging completed successfully.");
                    Progressbar.setValue(100);
                    btnWarp.setEnabled(true);

                    // Show a message when done
                    JOptionPane.showMessageDialog(null, "Converted successfully!", "Result", JOptionPane.INFORMATION_MESSAGE);
                } catch (InterruptedException | IOException e) {
                    e.printStackTrace();
                    printMessage("An error occurred: " + e.getMessage());
                    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            });

            packagingThread.start(); // Start the thread to execute the process
            
        } else {
            JOptionPane.showMessageDialog(null, "Please fill in all required fields.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnWarpActionPerformed

    private void printMessage(String message) {
        SwingUtilities.invokeLater(() -> txtAreaOutputResult.append(message + "\n"));
    }

    private void btnSelectIconPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectIconPathActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Icon File");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        // Set file filter for .ico files
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".ico");
            }

            @Override
            public String getDescription() {
                return "Icon Files (*.ico)";
            }
        });

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txticonPath.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSelectIconPathActionPerformed

    private void btnJarFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJarFileActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select JAR File");
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);  // Only JAR files allowed

        // Optionally, filter only JAR files
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".jar");
            }

            @Override
            public String getDescription() {
                return "JAR Files (*.jar)";
            }
        });

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txtJarFile.setText(selectedFile.getAbsolutePath());  // Set the JAR file name in txtJarFile
            jarDirectory = selectedFile.getParent();
            jarName = selectedFile.getName();
        }
    }//GEN-LAST:event_btnJarFileActionPerformed

    private void btnBrowseOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseOutputActionPerformed

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Select Output Directory");
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedDirectory = fileChooser.getSelectedFile();
            txtOutPut.setText(selectedDirectory.getAbsolutePath());
        }
    }//GEN-LAST:event_btnBrowseOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jartoexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jartoexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jartoexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jartoexe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new jartoexe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progressbar;
    private javax.swing.JButton btnBrowseOutput;
    private javax.swing.JButton btnJarFile;
    private javax.swing.JButton btnSelectIconPath;
    private javax.swing.JButton btnWarp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton rbtEXE;
    private javax.swing.JRadioButton rbtMSI;
    private javax.swing.JTextField txtAppName;
    private javax.swing.JTextField txtAppVersion;
    private javax.swing.JTextArea txtAreaOutputResult;
    private javax.swing.JTextField txtJarFile;
    private javax.swing.JTextField txtOutPut;
    private javax.swing.JTextField txtVendorName;
    private javax.swing.JTextField txticonPath;
    // End of variables declaration//GEN-END:variables
}
